version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    timezone: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Accept License Agreement of Android SDK Tools
          command: |
            echo y | android -s update sdk -u -a -t "tools"
            mkdir -p "$ANDROID_HOME"/licenses
            echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME"/licenses/android-sdk-license
            $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "extras;android;m2repository"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: build/test-results
