version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      ADB_INSTALL_TIMEOUT: 600
    steps:
      - checkout
      - run:
          name: Setup Emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Launch Emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Lint
          command: ./gradlew lint
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - run:
          name: Wait for Emulator
          command: circle-android wait-for-boot
      - run:
          name: Run Instrumented Tests
          command: ./gradlew connectedAndroidTest -PdisablePreDex
      - store_test_results:
          path: library/build/test-results
      - store_test_results:
          path: processor/build/test-results
      - store_test_results:
          path: processor/build/test-results
      - store_artifacts:
          path: library/build/reports
          destination: reports/library
      - store_artifacts:
          path: processor/build/reports
          destination: reports/processor
      - store_artifacts:
          path: sample/build/reports
          destination: reports/sample
      - run:
          name: Assemble AARs / JARs
          command: |
            ./gradlew library:assemble
            ./gradlew processor:assemble
      - store_artifacts:
          path: library/build/outputs/aar
          destination: artifacts/library
      - store_artifacts:
          path: library/build/libs
          destination: artifacts/library
      - store_artifacts:
          path: processor/build/libs
          destination: artifacts/processor
